import type { Appointment, Patient } from "@/app/types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "1",
    name: "Amari Belkacem",
    age: 24,
    address: "Sehaoula, Alger",
    lastConsultation: "2026-03-26",
    phone: "0550 12 34 56",
    gender: "M",
    profession: "Ingénieur",
    children: 0,
    familyStatus: "Célibataire",
  },
  {
    id: "2",
    name: "Mekhloufi Karima",
    age: 66,
    address: "1600, Tipaza",
    lastConsultation: "2026-03-26",
    phone: "0661 98 76 54",
    gender: "Mme",
    profession: "Retraitée",
    children: 3,
    familyStatus: "Marie(e)",
  },
  {
    id: "3",
    name: "Dahmani Zoubir",
    age: 77,
    address: "Oran, Centre",
    lastConsultation: "2026-03-26",
    phone: "0770 45 67 89",
    gender: "M",
    profession: "Retraité",
    children: 5,
    familyStatus: "Veuf/Veuve",
  },
  {
    id: "4",
    name: "Benali Samira",
    age: 31,
    address: "Bab Ezzouar, Alger",
    lastConsultation: "2026-03-24",
    phone: "0562 44 19 30",
    gender: "Mme",
    profession: "Architecte",
    children: 1,
    familyStatus: "Marie(e)",
  },
  {
    id: "5",
    name: "Bouzid Nabil",
    age: 42,
    address: "Sidi Bel Abbes",
    lastConsultation: "2026-03-22",
    phone: "0771 38 27 14",
    gender: "M",
    profession: "Commercant",
    children: 2,
    familyStatus: "Marie(e)",
  },
  {
    id: "6",
    name: "Kaci Lilia",
    age: 27,
    address: "Tizi Ouzou, Centre",
    lastConsultation: "2026-03-21",
    phone: "0664 50 11 92",
    gender: "Mlle",
    profession: "Enseignante",
    children: 0,
    familyStatus: "Célibataire",
  },
  {
    id: "7",
    name: "Mebarki Youcef",
    age: 54,
    address: "Setif, El Hidhab",
    lastConsultation: "2026-03-18",
    phone: "0553 74 62 08",
    gender: "M",
    profession: "Pharmacien",
    children: 4,
    familyStatus: "Marie(e)",
  },
  {
    id: "8",
    name: "Ferhat Nadjet",
    age: 63,
    address: "Constantine, Bardo",
    lastConsultation: "2026-03-16",
    phone: "0678 20 36 55",
    gender: "Mme",
    profession: "Retraitee",
    children: 5,
    familyStatus: "Veuf/Veuve",
  },
  {
    id: "9",
    name: "Ait Ouali Massinissa",
    age: 36,
    address: "Bejaia, Ihaddaden",
    lastConsultation: "2026-03-14",
    phone: "0549 88 71 43",
    gender: "M",
    profession: "Developpeur",
    children: 1,
    familyStatus: "Divorcé(e)",
  },
  {
    id: "10",
    name: "Saadi Amel",
    age: 29,
    address: "Annaba, Sidi Achour",
    lastConsultation: "2026-03-12",
    phone: "0790 31 24 67",
    gender: "Mme",
    profession: "Infirmiere",
    children: 0,
    familyStatus: "Célibataire",
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: "1",
    patientName: "Jean Dupont",
    type: "Consultation de suivi",
    time: "09:00",
    date: "2024-10-15",
    status: "normal",
  },
  {
    id: "2",
    patientName: "Marie Lefebvre",
    type: "Vaccination",
    time: "09:00",
    date: "2024-10-15",
    status: "normal",
  },
  {
    id: "3",
    patientName: "Lucas Bernard",
    type: "Examen annuel complet",
    time: "10:00",
    date: "2024-10-15",
    status: "urgent",
  },
];
