PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS patient (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NUM_CARTE TEXT,
  NOM TEXT NOT NULL,
  PRENOM TEXT NOT NULL,
  AGE INTEGER,
  AGE_MOIS INTEGER DEFAULT 0,
  SEXE TEXT,
  PROFESSION TEXT,
  ETAT_FAMILIAL TEXT,
  ENFANTS INTEGER DEFAULT 0,
  ADRESSE TEXT,
  TEL TEXT,
  POIDS_KG REAL,
  TAILLE_CM REAL,
  ANTECEDENTS_PERSONNELS TEXT,
  ANTECEDENTS_FAMILIAUX TEXT,
  NOTE TEXT,
  CREATED_AT TEXT DEFAULT (datetime('now')),
  UPDATED_AT TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS consultation (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONSTAT TEXT,
  DIAGNOSTIC TEXT,
  EXPLORATION TEXT,
  MALADIE TEXT,
  TRAITEMENT TEXT,
  NOTE TEXT,
  DATE TEXT,
  HEURE TEXT,
  TARIF INTEGER,
  ID_PATIENT INTEGER NOT NULL,
  FOREIGN KEY (ID_PATIENT) REFERENCES patient(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS arretmaladie (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TEXT TEXT NOT NULL,
  DATEDEBUT TEXT NOT NULL,
  DATEFIN TEXT NOT NULL,
  ID_PATIENT INTEGER NOT NULL,
  ID_CONSULT INTEGER NOT NULL,
  FOREIGN KEY (ID_PATIENT) REFERENCES patient(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_CONSULT) REFERENCES consultation(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS arretravail (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TEXT TEXT NOT NULL,
  DATEDEBUT TEXT NOT NULL,
  DATEFIN TEXT NOT NULL,
  ID_PATIENT INTEGER NOT NULL,
  ID_CONSULT INTEGER NOT NULL,
  FOREIGN KEY (ID_PATIENT) REFERENCES patient(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_CONSULT) REFERENCES consultation(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bilan (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  AVANT TEXT NOT NULL,
  BILAN TEXT NOT NULL,
  SALUT TEXT NOT NULL,
  ID_PATIENT INTEGER NOT NULL,
  ID_CONSULT INTEGER NOT NULL,
  FOREIGN KEY (ID_PATIENT) REFERENCES patient(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_CONSULT) REFERENCES consultation(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ordonnance (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MEDICAMENT TEXT NOT NULL,
  TYPE TEXT NOT NULL,
  PRISE TEXT NOT NULL,
  DUREE TEXT NOT NULL,
  ID_PATIENT INTEGER NOT NULL,
  ID_CONSULT INTEGER NOT NULL,
  FOREIGN KEY (ID_PATIENT) REFERENCES patient(ID) ON DELETE CASCADE,
  FOREIGN KEY (ID_CONSULT) REFERENCES consultation(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS rdv (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PATIENT INTEGER NOT NULL,
  DATE TEXT NOT NULL,
  CONSULT INTEGER,
  ETAT INTEGER,
  FOREIGN KEY (ID_PATIENT) REFERENCES patient(ID) ON DELETE CASCADE,
  FOREIGN KEY (CONSULT) REFERENCES consultation(ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS login (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  login TEXT NOT NULL,
  password TEXT NOT NULL,
  Nom TEXT NOT NULL,
  Prenom TEXT NOT NULL,
  Specialite TEXT NOT NULL,
  Adresse TEXT NOT NULL,
  Ville TEXT NOT NULL,
  Tel TEXT NOT NULL,
  mail TEXT NOT NULL,
  lastaccess TEXT,
  IP TEXT
);

CREATE TABLE IF NOT EXISTS message (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NOM TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  TEL TEXT NOT NULL,
  MESSAGE TEXT NOT NULL,
  MEDECIN TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_consultation_patient ON consultation(ID_PATIENT);
CREATE INDEX IF NOT EXISTS idx_rdv_patient ON rdv(ID_PATIENT);
CREATE INDEX IF NOT EXISTS idx_arretmaladie_patient ON arretmaladie(ID_PATIENT);
CREATE INDEX IF NOT EXISTS idx_arretravail_patient ON arretravail(ID_PATIENT);
CREATE INDEX IF NOT EXISTS idx_bilan_patient ON bilan(ID_PATIENT);
CREATE INDEX IF NOT EXISTS idx_ordonnance_patient ON ordonnance(ID_PATIENT);
